quarkus.http.port=8088

# PostgreSQL datasource (Docker local container)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/store

# Hibernate: DDL runs on startup; creates tables if they don't exist, updates schema if entity changed
quarkus.hibernate-orm.database.generation=update
